new post: add 2023 sponsor cathay post
pycontw/pycontw-blog pull request #56
Opened 2023-10-24 07:10 UTC by kevin1kevin1k

Original draft at [google docs](https://docs.google.com/document/d/1S4XpIcCZr5c0Zta9ld97nZcsM-SU-_aeJ0viq-qOjxI/edit?usp=sharing)

## Types of changes

* new post

## Description

Add a new post for platinum sponsor Cathay of PyCon TW 2023

2023-10-27 02:04 UTC, Lee-W commented on content/posts/2023-10-25-pycon-tw-2023-sponsor-cathay.md
> +| 國泰金控DDT         | 資料科學工程師(Python程式開發)                 | <a href="https://www.104.com.tw/job/6w7ov" target="_blank">https://www.104.com.tw/job/6w7ov</a> |   |   |
May I know why we don't use `[]()` syntax for links here?

2023-11-20 02:05 UTC, winniepopu approved these changes
LGTM, Thank you!

2023-11-20 11:50 UTC, Lee-W requested changes

2023-11-20 11:50 UTC, Lee-W commented on content/posts/2023-11-12-pycon-tw-2023-sponsor-cathay.md
> +Date: 2023-11-12 21:00
```suggestion
Date: 2023-11-20 21:00
```

2023-11-20 11:50 UTC, Lee-W commented on content/posts/2023-11-12-pycon-tw-2023-sponsor-cathay.md
> +|                     |                                                |                                                               |   |   |
```suggestion
```

2023-11-23 00:06 UTC, Lee-W approved these changes
I just resolved my comments on my side. @kevin1kevin1k Thanks for helping out.

2023-11-23 00:09 UTC, merged