new post: add PyCon TW 2024 call for proposal
pycontw/pycontw-blog pull request #94
Opened 2024-02-29 01:43 UTC by Anna0118

## Types of changes
* post update

## Description

1.  Add new post: PyCon TW 2024 call for proposals
2.  The post is available in Chinese and English

Please help me check the content. Thanks a lot.

2024-02-29 14:21 UTC, winniepopu requested changes
Hi Anna,

I've reviewed the content, and it's excellent!
I have some suggestions for this post:

1. Adding a text summary would make it more attractive, especially if it includes images and text on the homepage.
2. It would be better to also add the picture to the article page.
3. The picture has some flaws Orz. I've generated a new version. Please replace it with the new one: https://drive.google.com/drive/u/1/folders/13iX5OzJngtc8DISPSg7584lD593jIqWu.

I think the article is awesome! Thanks for your contribution!

2024-02-29 14:21 UTC, winniepopu commented on content/posts/2024-02-28-pycon-taiwan-2024-cfp-is-open.md
> +<!--your content here-->
I think this line can just be removed.

2024-03-01 15:01 UTC, winniepopu approved these changes
Hi Anna, yeah it looks great! Thank you!
BTW, I think it would look better to not to restrict the picture with width = 500 in the article page haha~

2024-03-02 02:28 UTC, Anna0118 commented
> Hi Anna, yeah it looks great! Thank you! BTW, I think it would look better to not to restrict the picture with width = 500 in the article page haha~

Thanks a ton for the comment. And yes, you're absolutely right... Next time, no width restrictions necessary!

2024-03-03 09:44 UTC, merged